### PR TITLE
Feature/152 email html format

### PR DESCRIPTION
**Pull request by TFAstudio**
Issue #152: Honour carriage returns in Message field for email handler. (Umbraco v7)

* Add Regex reference
* Replace \n, \r and/or \r\n breaks added to "message" field with <br /> for HTML formatted part of email

### CODE REVIEW

**Comment by TFAstudio** [comment]
There is two fields that are combined in the `baseMessage` - the `config.Message` and the `extraMessage`.  These are the only values that are being modified by me.

I am assuming that `config.Message` is the field we are trying to allow the line breaks to show as `<br \>` in the HTML formatting.  However, I am a little at a loss to know where the `extraMessage` info is actually coming from?  I see there is an `ExtraMessageKey` with a value of `"Formulate Core: Email: Extra Message"`, but I am not quite sure where this fits.  

> IIRC, there is a formatting function on every field with an enum that allows you to format the value specially for emails. I can't recall if that allows for HTML, but it's something to look into.

This is not one of the form fields that is captured data, but rather the message that we are trying to format is the `Message` text area in the `EmailHandler` tab.  If this is still what you mean, a little extra info would be appreciated to get the development just right.

I am happy to narrow down our modifications to only the `config.Message`, but I will have to change how the information is sent into the `ConstructMessage()` method, since the `baseMessage` is combined and sent before we check to see whether we are using HTML formatting with the `isHtml` flag.

Thanks again

**Comment by Nicholas-Westby** [comment]
I'm not really following your discussion of `Message` / `baseMessage`, and `extraMessage`. Perhaps when I said "field" above you interpreted that as "C# variable or property"?

What I meant by "field value" was "a value submitted to the Formulate form during an AJAX submission". So, the first name, last name, and whatever other fields might be on a given form.

And I was saying "field value" rather than just "field" because it is the value in particular that would need this treatment. The field label wouldn't need it. The other aspects of the email wouldn't need it either. Just the field values.

Hopefully that clears things up a bit.

Here's one line that may make this a bit more clear: https://github.com/rhythmagency/formulate/blob/master/src/formulate.app/Forms/Handlers/Email/EmailHandler.cs#L469

```cs
formatted = field.FormatValue(values, FieldPresentationFormats.Email);
```

That is what gets a field value in a given format (`FieldPresentationFormats.Email` in this case).

This line might cause you a bit of trouble: https://github.com/rhythmagency/formulate/blob/master/src/formulate.app/Forms/Handlers/Email/EmailHandler.cs#L509

```cs
lines = lines.Select(x => WebUtility.HtmlEncode(x)).ToList();
```

Because it's doing some HTML encoding. Now that you will be injecting HTML into the values, you'll have to handle the HTML encoding a bit differently, keeping in mind there are two versions of each email (plain text and HTML).

What you'll likely have to do is HTML encode the value first, then inject the BR tags. And you'll also have to make sure the other parts of the email get HTML encoded too since you'll need to remove that line that just HTML encodes everything at once.

**Comment by TFAstudio** [comment]
We are definitely talking about two different things here.  I have taken a screenshot and labeled the information we are actually trying to add HTML line breaks to:
Formulate_handlers

As you can see in the image, this has nothing to do with fields that are being captured by the form input, but rather the message in the EmailHandler Message that will be sent to every email handler recipient.

> Now that you will be injecting HTML into the values, you'll have to handle the HTML encoding a bit differently, keeping in mind there are two versions of each email (plain text and HTML).

By doing a diff on the code (I think I need to update the branch, I apologize, I did not realize that this was previously forked by you so it needs merging with the current master), you will see that I am not touching the fields captured by the form.

> What you'll likely have to do is HTML encode the value first, then inject the BR tags. And you'll also have to make sure the other parts of the email get HTML encoded too since you'll need to remove that line that just HTML encodes everything at once.

I am aware, which is why the encoding and transforming of the `\n` to `<br />` is only done in the block that checks to see if `isHtml` is `true`.

``` c#
            // HTML encode?
            if (isHtml)
            {
                baseMessage = WebUtility.HtmlEncode(baseMessage);
                // just in case other browsers enter new lines differently, cater to all three
                baseMessage = Regex.Replace(baseMessage, @"\r\n?|\n", "<br />");
                lines = lines.Select(x => WebUtility.HtmlEncode(x)).ToList();
            }


            // Return message.
            return baseMessage + nl + string.Join(nl, lines);
```

Apart from adding the using statement for `Regex`, there is only one line and a comment that I added.

I hope this helps to clarify what it is we are trying to achieve and what it is that I did.

**Comment by Nicholas-Westby** [comment]
I see now. I though you were trying to format the "Message" field (submitted by the user) and you are instead formatting the "Message" field (specified in the back office).

I'll go ahead and merge in the pull request soon.

**Comment by jamiepollock** [comment]
I've updated the base to merge this into `develop` so we can test this before it goes into the `master` branch.

**Pull request merged**
