### PR TITLE
Duplicate Forms

### PR DESCRIPTION
**Pull request by ADAS-antonio-calatayud**
Hello!

First of all, thank you very much for your project! I'm using your forms in one project, where I had to duplicate a form a few times. I saw that you don't have that functionality so I developed my self.

Sorry, but I didn't realize that you had a "v3/develop" branch, so I did the changes on the "v3/master" branch and then merged them into the "v3/develop" and then do a pull request.

Please have a look and check if the code matches your project standards.

Also, I tried to use "icomoon" to generate a new icon for the new functionality, but it didn't work. 

All the best,

Antonio

### CODE REVIEW

**Comment by Nicholas-Westby** [comment]
Hi Antonio,

Thanks for this!

I'll need to clean up a few things, but overall this looks like a solid contribution. In case you have time before I do, here are the things I want to clean up:

* Ensure code comments are consistent (they mostly were, with a couple missing spots).
* Address the couple of TODO comments.
* Ensure the layout is also duplicated (will need to have the layout duplicate itself since the layout system is extensible with custom layouts).
* Ensure duplicates have new names (maybe this is already happening, but didn't notice).

Let's keep communication open so we can avoid duplicate work.

Here's the issue that corresponds to this pull request: https://github.com/rhythmagency/formulate/issues/18

**Comment by ADAS-antonio-calatayud** [comment]
Hi Nicholas,

No worries, thanks to you guys for this project!

I have some time this morning, so I will try to improve the code following your comments.

**Comment by ADAS-antonio-calatayud** [comment]
Hi again,

I have done the following modifications:

1. Get the layouts from the existing form.
2. Duplicate them with new names (_duplicated). I added them into a dictionary as some configurations can share the same layout, so we don't want to duplicate layouts for each configuration.
3. Add new duplicated form Id to the layout.
4. I wasn't able to achieve this, but I guess the field Ids should be changed to the new duplicated form on the `layout.Configuration` property?
5. Duplicate form configurations with the new layouts. It checks if the configuration has a layout or not. 

Things that I wasn't sure:
1. If a layout is inside a folder, what should we do? At the moment, that layout is skipped as seems quite tricky to achieve this.
2. Configuration should be renamed too?

Hope this helps.

All the best,

Antonio

**Comment by Nicholas-Westby** [comment]
Hi Antonio,

Thanks for the updates.

I wouldn't worry about the field ID's being regenerated. I don't see the harm in keeping them the same, and I can't think of a use case where it would help to change them.

I would think a layout within a folder should be duplicated within that same folder. IIRC, there is something like a "Path" property that contains a list of ID's that are the ancestors of a given layout.

I'm on the fence about the configuration names. Let's just leave them unchanged and we can revise that later if we need to.

Thanks again, and I'll take a deeper look and pull this in when I get a chance (hopefully this week/weekend).

**Comment by Nicholas-Westby** [comment]
FYI, I've pulled this into a feature branch and am tinkering with it a bit.

**Comment by Nicholas-Westby** [comment]
I cleaned it up a bit and merged it into the v3/develop branch. See commit here: https://github.com/rhythmagency/formulate/commit/7683576682473f5cf1c12c34c67796497ed60064

Thanks for implementing this, @antonio-calatayud! It'll be part of the next Formulate release.

**Comment by ADAS-antonio-calatayud** [comment]
No problems! Hope the feature is useful for other users.
Cheers

**Pull request merged**
